name: build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Generate Gradle Wrapper
        run: |
          gradle wrapper --gradle-version 8.10.2
      - name: Build with Gradle
        run: |
          ./gradlew --version
          ./gradlew build -x test --no-daemon
      - name: Archive JAR
        uses: actions/upload-artifact@v4
        with:
          name: NeXTQuarry-jar
          path: build/libs/*.jar
